### ISSUE TITLE
strange view

### ISSUE THREAD

**Issue by tigrazone** [WilliamLewww/vulkan_ray_tracing_minimal_abstraction#15]
Hello.
I compiled ray_query example and see this
![image](https://user-images.githubusercontent.com/3808839/209564483-481588d4-c629-4fb9-b349-e5715842e5bb.png)
how to fix it?
windows 10, rtx 3060, minGW

**Comment by tigrazone** [comment]
one more question. how to make resizable window?

**Comment by WilliamLewww** [comment]
Oh, I think it might be like that because the camera position starts on the ground. Could you hit "SPACE" to see if that raises the view?

To make the window resizable, you will need to add code to the resize hook. This would include recreating the swapchain with images to the correct size. https://vulkan-tutorial.com/Drawing_a_triangle/Swap_chain_recreation

**Comment by tigrazone** [comment]
thank you. SPACE helps. with WASD i make camera which look at scene well
